### ISSUE TITLE
Update Node.js version for generator

### ISSUE THREAD

**Issue by racse1** [kraftvaerk/generator-rammevaerk#16]
This is a follow-up to #10. We need to update required Node.js version in `.travis.yml` and [`package.json`](https://github.com/kraftvaerk/generator-rammevaerk/blob/master/package.json), so we're aligned with the version we use in the app itself.

Additionally, I think, it makes sense to update generator's dependencies alongside with Node.js version.

**Comment by mi2oon** [comment]
I think I tried updating a little while back and gave up really fast as I saw yeoman-generator dep was updated. Anyway, I might give it another chance this coming weekend ;)
