### ISSUE TITLE
Use Browserslist

### ISSUE THREAD

**Issue by racse1** [kraftvaerk/generator-rammevaerk#2]
Hi there,

I'm thinking, maybe it's a good idea to use [Browserslist](https://github.com/ai/browserslist) (via `.browserslistrc`) instead of [config entry](https://github.com/kraftvaerk/generator-rammevaerk/blob/master/app/templates/project-name.Gulp/config.js#L26-L33)? Autoprefixer already supports it out of box. babel-preset-env also is also going to [support it](https://github.com/babel/babel/blob/38355d92308867db501f2eb2f8139d0df2089ee5/experimental/babel-preset-env/src/targets-parser.js#L104) starting from next version, I believe.

Then we can potentially remove explicit configuration from [here](https://github.com/kraftvaerk/generator-rammevaerk/blob/master/app/templates/_webpack.config.js#L30) and [here](https://github.com/kraftvaerk/generator-rammevaerk/blob/master/app/templates/project-name.Gulp/tasks/styles.js#L16).

I can create a feature branch for now and we can merge it later once babel-preset-env gets released. How does it sound?

Thanks

**Comment by mi2oon** [comment]
🎉1st issue @racse1  👯 

Great to see someone actually looking though and giving suggestions. For years  it's basically only been me. It is important to have a on going to at this as this generator serves as a base of all of our new projects.

Nevertheless, it's a great idea to use  Browserslist (via `.browserslistrc`) The config entry was just some old code waiting to be removed when bable preset env started supporting it.

But just go ahead and create that feature branch and lets wait for the next version of Bable.. it has a lot of other goodies regarding smarter transpiling too.. so can't wait :D

**Comment by racse1** [comment]
@mi2oon Glad to help! I wish I would've done it earlier, though. Let's try to keep the ball rolling 😄
