### ISSUE TITLE
gulp-watch plugin 

### ISSUE THREAD

**Issue by racse1** [kraftvaerk/generator-rammevaerk#22]
Hello,

I can see that currently we use [`gulp-watch`](https://github.com/kraftvaerk/generator-rammevaerk/blob/master/app/templates/PACKAGE/_DEPENDENCIES.json#L36) to view the changes and perform the corresponding tasks. Are there any advantages to using this over [`gulp.watch`](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpwatchglob--opts-tasks-or-gulpwatchglob--opts-cb)? It just looks like an unnecessary dependency, but maybe it has some benefits that I don't know about ...

Thanks

**Comment by mi2oon** [comment]
I am not quite sure if things have changed. But back in the days the watch plugin could handle deletion, adding and renaming of files much better without having to restart the whole task. Hope this makes sense.. But it would be a good idea to retest it... perhaps things have changed. :)

**Comment by racse1** [comment]
@mi2oon Thanks, good points! I'll check whether things have changed 🙂
