### ISSUE TITLE
gulp-rimraf is deprecated

### ISSUE THREAD

**Issue by AnastasiaRed** [kraftvaerk/generator-rammevaerk#23]
Hi all,
We use 'gulp-rimraf' plugin for cleaning tasks. 
But [documentation](https://github.com/robrich/gulp-rimraf) said that it is deprecated in favor of ['del'](https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md). 
If there is no special reasons why we use it, i think it would be nice to update

Thanks

**Comment by racse1** [comment]
I totally agree, in fact, del is much easier to use 😄 @AnastasiaRed would you like to submit a PR for that?

**Comment by mi2oon** [comment]
👍
