### ISSUE TITLE
More ES6

### ISSUE THREAD

**Issue by racse1** [kraftvaerk/generator-rammevaerk#29]
Hi @mi2oon,

I've noticed we have a bit of mismatch in the code. I guess, it mostly related to the ongoing ES5 to ES6 (I use ES6 as a collective term of all new things we support) transition.

So I would like to help and look at some parts of the codebase that might be potentially updated. Some examples:

* `module.exports = { pkg: pkg };` => `module.exports = { pkg };`
* `function () {}` => arrow equivalent that makes sense (`() => {}`, `() => ()`, `() => true`)
* `baseDir + '/Mockup'` => <code>&#96;${baseDir}/Mockup&#96;</code> (this is a bit opinionated I guess, but I use template strings everywhere for consistency, what's your take on that?)
* `if (!global.isWatching) { processors.push(require('cssnano')); }` => `const processors = [...global.isWatching ? [] : [require('cssnano')]]`
* `Object.assign(elm.data(), { padding: 10 });` => `{ ...elm.data(), padding: 10 }`

Does it make sense? What do you think? 😄 

Thanks

---

A side question 😄 , when you have something like that:

```
const del             = require('del');
const gulp            = require('gulp');
const gutil           = require('gulp-util');
```

How do you know how much space it needs to be between variable name and `=`? It varies from one file to another, so I can't really make a sense of it 😞

I used to see a style with the following logic behind:

```
const del  = require('del');
const gulp = require('gulp');
```

Then, at some point, a thing with relatevely long name comes, so:

```
const del                                = require('del');
const gulp                               = require('gulp');
const longerThanGulpSoMoveEverythingElse = require('best-one');
```

**Comment by mi2oon** [comment]
Hi @racse1,

Not to forget all this. I think you have great points all across the list. Even the opinionated one. I like the fact of keeping everything consistent. I don't know why using template string for me has always felt heavy for me. Perhaps it's just a underlying mental environmentalist trying to save a CPU cycle somewhere 🌲 

As for the side question, well it's pure insanity at work 😁  I use to have a align plugin for sublime back in the days. That's where it is from. But you are right maintaining those spaces manually can drive you insane. Also then do we only do that alignment for top vars or all vars. 

Anyway, I would probably drop this super alignment for the future 🌬
