### ISSUE TITLE
Make better use of config.js

### ISSUE THREAD

**Issue by racse1** [kraftvaerk/generator-rammevaerk#36]
Hi everyone,

I'm thinking maybe it'd be nice to extend our [`config.js`](https://github.com/kraftvaerk/generator-rammevaerk/blob/master/app/templates/project-name.Gulp/config.js), because currently it's only being used for paths.

Idea is to use the config for any options we have, a quick example will explain it better than me:

```js
export default {
    ...

    <NAME_OF_FEATURE>: {
        paths: {
            src: <SRC>,
            dest: <DEST>
        },
        <NAME_OF_FIST_PLUGIN>: <OPTIONS_OF_FIST_PLUGIN>,
        <NAME_OF_N_PLUGIN>: <OPTIONS_OF_N_PLUGIN>
    },

    mockup: {
        paths: {
            dest: `${baseDir}/Mockup`,
            src: `${baseDir}/Mockup`
        },
        pug: {
            data: {
                site: {
                    ...
                }
            },
            pretty: true
        }
    },

    ...
};
```

* `NAME_OF_FEATURE` is an exact name of a related task, so we have more consistency. Currently we have `html`, `css`, `js` in the config vs. `html`, `styles`, `scripts` in the task names. I believe we should stick to either a task name or to an extension, but please correct me if I'm wrong on the whole naming point 😄 
* `NAME_OF_N_PLUGIN` is an exact name of a plugin or tool is being used (e.g. `sass`, `pug`).

One of the benefits I see in this approach is that we're going to improve developer experience by abstracting configuration out of logic, so in most cases you'll only need to change the config a little bit in order to adjust things. Also logic will be more clean as all configuration-related stuff will be removed.

What do you think? 😄 

Thanks

**Comment by mi2oon** [comment]
@racse1 I like the benefits and as you correctly point this abstraction does have it's shine. However, I actually never really liked the fact of abstracting plugin options aways and the reason for that is mainly if a developer needs to fiddle around with those option he/she should have a better understanding of the logic behind it. Therefore having an abstrations also servers as a black box which I would like to avoid. What do you think about that?

**Comment by racse1** [comment]
@mi2oon Yeah... I didn't think about that, so a developer would actually have to learn what's going on there, agree 👍  However I still like the idea of unifying filenames and tasks, but that's a separate matter, if it makes sense 😄

**Comment by mi2oon** [comment]
@racse1 I totally agree to that 😁
