### ISSUE TITLE
Scoped npm packages

### ISSUE THREAD

**Issue by racse1** [kraftvaerk/generator-rammevaerk#38]
Hi everyone,

What do you think about moving all our packages under [`kraftvaerk` scope](https://www.npmjs.com/docs/orgs/)?

- [ ] `generator-rammevaerk` => `@kraftvaerk/generator-rammevaerk`
- [x] `eslint-config-kraftvaerk` => [`@kraftvaerk/eslint-config`](https://github.com/kraftvaerk/eslint-config-kraftvaerk/commit/714047a2230c0c282e0a5487a04382b7dbd1009c)
- [x] `stylelint-config-kraftvaerk` => [`@kraftvaerk/stylelint-config`](https://github.com/kraftvaerk/stylelint-config-kraftvaerk/commit/191baef5ea9fd945fd0a450632e71a4747f4af00)
- [x] `kv.cookieconsent` => [`@kraftvaerk/cookieconsent`](https://github.com/kraftvaerk/cookie-consent/commit/fa7efb3153d88a612db3ab7d05dccbff0ca560f4)

I'm a bit uncertain about shareable configs, because I think it makes sense to use same name for repo and npm package, so maybe we can just stick to what we currently have (e.g. `@kraftvaerk/eslint-config-kraftvaerk`).

**Comment by mi2oon** [comment]
I would love that.. I'll have a look at the npm part. However, what about the repos on git? Should we then also move to a mono-repo structure?

**Comment by racse1** [comment]
@mi2oon Well, that's completely up to us. I mean having a scope doesn't force us to go monorepo, does it? 😄 I doubt we actually need a monorepo — our packages can be perfectly used independently and we don't have to fiddle with Lerna or think about structuring issues and pull requests.

If you think it'd be better with monorepo — I'm happy to know why 👍 At the same time I think it's very convenient way of handling large number of, let's say, helpers or components.

**Comment by racse1** [comment]
Description updated 👆

**Comment by mi2oon** [comment]
@racse1 Updated little more. I decided to keep things pretty much like more switched to scoped on npm.
