### ISSUE TITLE
Fix watch task

### ISSUE THREAD

**Issue by racse1** [kraftvaerk/generator-rammevaerk#40]
Hi, currently we don't use webpack's watch mode and that gives us very slow build times.

**Comment by mi2oon** [comment]
@racse1 I don't think we can use the watch mode together with browserSync but I might be wrong.

**Comment by racse1** [comment]
@mi2oon We sure can, or at least we used to 😄, here's an example from one of the projects https://gist.github.com/racse1/cc1b584cc66227d8b179111389f150ef (Gulp tasks).

**Comment by mi2oon** [comment]
@racse1 Then I see no reason not to have watch mode on when we are in gulp watch mode :)
