### ISSUE TITLE
Error 'key' is defined but never used - no-unused-vars

### ISSUE THREAD

**Issue by rammi987** [kraftvaerk/generator-rammevaerk#45]
const obj = { a: 5, b: 7, c: 9 };
Object.entries(obj).forEach(([key, value]) => {
  console.log(`${value}`); // "a 5", "b 7", "c 9"
});

This follow code above is valid in ES6, but the eslint complaning about unused.

**Comment by racse1** [comment]
Hi @rammi987,

We can certainly think about how we want to handle unused arguments, but in your case you can simply use `Object.values(obj)` instead 😄 

In general, ESLint issues aren't directly related to the generator itself, so we should probably keep those in [kraftvaerk/eslint-config-kraftvaerk](https://github.com/kraftvaerk/eslint-config-kraftvaerk).

**Comment by rammi987** [comment]
@racse1 you are right kraftvaerk/eslint-config-kraftvaerk is the correct place for this issue, my bad.
