### ISSUE TITLE
Update README.md and add LICENSE

### ISSUE THREAD

**Issue by racse1** [kraftvaerk/generator-rammevaerk#5]
Hi there,

I want to visually improve our repo a tiny bit, hope you don't mind 😄 Please let me know if it makes sense or if I'm missing something.

**`README.md`**

* Update badges. Currently click on them leads us nowhere (except build one). Probably it'd be nice to use [David DM](https://david-dm.org/) for dependencies and I'm pretty sure there's something out there for npm releases as well.
* Update code block in Install section by adding `yo` dependency (`npm install -g yo generator-rammevaerk`). Or maybe make a separate step for Yeoman installation. I think, this will save time if user hasn't used it before.
* Remove `$` from code blocks as it makes it harder to copy-paste. Fix code block for `$ yo doctor`.
* Minor typo here and there.

**`LICENSE`**

Probably it'd be a good idea to add `LICENSE` file, so repo will get this nice license indicator:

![License indicator](https://help.github.com/assets/images/help/repository/repo-license-indicator.png)

Thanks

**Comment by mi2oon** [comment]
What are we waiting for... I don't mind at all it all sounds good so lets make it look good 😎
