### ISSUE TITLE
Move to Terser from UglifyJS

### ISSUE THREAD

**Issue by mi2oon** [kraftvaerk/generator-rammevaerk#51]
Why choose [Terser](https://github.com/terser-js/terser)? uglify-es is no longer maintained and uglify-js does not support ES6+. Also it has potential speed improvements([pref](https://github.com/webpack-contrib/terser-webpack-plugin/issues/15)) and webpack team is already using it. 

Any thoughts @kraftvaerk/frontend?

**Comment by racse1** [comment]
@mi2oon that's also a good one 👍 I think we may just make this switch alongside with the transition to upcoming webpack 5 release.

**Comment by mi2oon** [comment]
@racse1 Agree, let's wait for the v5. 👍  However, I've already done some pref on existing projects and didn't see a huge difference 🍷

**Comment by racse1** [comment]
@mi2oon yeah, you're right. They use it by default nowadays (when you use kind of empty config with `mode` set to `production`).

**Comment by mi2oon** [comment]
> I think the huge difference comes when you don't compile for IE11. I'm currently working out a way to support separate bundles for IE. Haven't figured the best way yet though, looks a bit messy when you have too much webpack configs

@racse1  Wow, I've been looking into that too and haven't been able to find a good way. But I hope we can get a non messy version. It's a bit sad to see the code getting transpiled to the lowest common denominator. ⚫️ 

> @mi2oon yeah, you're right. They use it by default nowadays (when you use kind of empty config with mode set to production).

@racse1  I didn't know exactly when they where using it. But nice, perhaps we should just switch before v5 as it's not that hard. I can create a PR 🎟

**Comment by kristoforsalmin** [comment]
Hey @mi2oon, sorry, completely missed a couple of your last comments.

I've got some updates on IE 11 thing, looks pretty good with [webpack-merge](https://github.com/survivejs/webpack-merge). I'll follow up with the details a bit later (perhaps a separate issue).

Regarding Terser, cool, looking forward 😀 I think we can just remove:

https://github.com/kraftvaerk/generator-rammevaerk/blob/master/app/templates/_webpack.config.js#L41-L46

And we're good to go 😉

**Comment by kristoforsalmin** [comment]
Fixed in #55.
