### ISSUE TITLE
New solutions "UNEMET PEER DEPENDENCY" on bootstrap

### ISSUE THREAD

**Issue by rammi987** [kraftvaerk/generator-rammevaerk#8]
When installing a new solutions, for bootstrap - bootstrap has a dependency for Propper.js witch in the installing gives an error "UNEMET PEER DEPENDENCY"

So problem is when include all Bootstrap JavaScript library it will fail - Webpack will not find Propper.js

**Comment by racse1** [comment]
@rammi987 In theory it should be a warning, not an error. I also have experienced that. I guess, it depends on whether we use Bootstrap's tooltips, popovers and dropdowns or not. There's no point including Popper.js if we don't use those features.

So, do you guys use them?

I'm not a fan of Bootstrap, so it's totally up to you 😄

**Comment by racse1** [comment]
@rammi987 Do you have any other suggestions or we shall close this one? Personally, I think the best way is to individually decide whether you need to use Popper.js for a given project or not.

**Comment by mi2oon** [comment]
@rammi987 @racse1 I agree, Popper is not always needed and thus I would also only include it when needed. Personally I like when it breaks stuff, makes one think what is being included and why. 

I consider this one closed unless you guys have anything else to add. 😄

**Comment by mi2oon** [comment]
closed
